# Generated by Django 3.0.6 on 2020-05-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_age', models.IntegerField()),
                ('patient_sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8)),
                ('patient_weight', models.FloatField(null=True)),
                ('patient_contact', models.CharField(max_length=10)),
                ('patient_date_of_birth', models.DateField(null=True)),
                ('postal_address', models.CharField(max_length=150, null=True)),
                ('drug_class', models.CharField(max_length=150, null=True)),
                ('drug_name', models.CharField(max_length=150)),
                ('drug_form', models.CharField(choices=[('CAPSULE', 'CAPSULE'), ('TABLET', 'TABLET'), ('OINTMENT', 'OINTMENT'), ('INJECTION', 'INJECTION')], max_length=50)),
                ('channel', models.CharField(choices=[('ORALLY', 'ORALLY'), ('INTRAVENOUS', 'INTRAVENOUS')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('dosage', models.TextField()),
                ('precaution', models.TextField(null=True)),
                ('side_effect', models.TextField(null=True)),
                ('date_of_issue', models.DateField()),
                ('end_date', models.DateField()),
                ('administer_name', models.CharField(max_length=150)),
                ('administer_contact', models.CharField(max_length=10)),
                ('name_of_pharmacy', models.CharField(max_length=150)),
                ('pharmacy_address', models.CharField(max_length=150)),
            ],
        ),
    ]
