# Generated by Django 3.0.6 on 2020-05-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='channel',
            field=models.CharField(choices=[('ORAL', 'ORAL'), ('INTRAVENOUS', 'INTRAVENOUS')], default='ORAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='drug_form',
            field=models.CharField(choices=[('CAPSULE', 'CAPSULE'), ('TABLET', 'TABLET'), ('OINTMENT', 'OINTMENT'), ('INJECTION', 'INJECTION')], default='CAPSULE', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=8),
        ),
    ]
